name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: sudo apt-get install -y flex
    - name: build the app
      run: mkdir build && cd build && cmake .. && cmake --build .
    - name: test
      run: ./build/TESTS_LEXER
